version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: fastapi_db
    restart: always
    volumes:
      - ./fastapi_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi_user 
      POSTGRES_PASSWORD: fastapi
      PGDATA: /fastapi
